-- super-coder MAP authored layer — GENERATED by scripts/snapshot.py.
-- The cartographer-curated sections of the map DB (.sc-state/map.db).
-- Idempotent; reloaded into a fresh map DB by map_db.seed_authored().
-- The rest of the map (files/deps/env) is a derived cache — re-mapped,
-- not snapshotted. Do not hand-edit — curate via the shell, then snapshot.

BEGIN;

DELETE FROM dr_section;
INSERT INTO dr_section (section_id, name, path_prefix, description, sort_order) VALUES (1, '.github', '.github/', NULL, 0);
INSERT INTO dr_section (section_id, name, path_prefix, description, sort_order) VALUES (2, 'installer', 'installer/', NULL, 1);
INSERT INTO dr_section (section_id, name, path_prefix, description, sort_order) VALUES (3, 'installer-r27', 'installer-r27/', NULL, 2);
INSERT INTO dr_section (section_id, name, path_prefix, description, sort_order) VALUES (4, 'shared', 'shared/', NULL, 3);
INSERT INTO dr_section (section_id, name, path_prefix, description, sort_order) VALUES (5, 'spike', 'spike/', NULL, 4);
INSERT INTO dr_section (section_id, name, path_prefix, description, sort_order) VALUES (6, 'src', 'src/', NULL, 5);

COMMIT;
