-- super-coder MAP authored layer — GENERATED by scripts/snapshot.py.
-- The cartographer-curated sections of the map DB (.sc-state/map.db).
-- Idempotent; reloaded into a fresh map DB by map_db.seed_authored().
-- The rest of the map (files/deps/env) is a derived cache — re-mapped,
-- not snapshotted. Do not hand-edit — curate via the shell, then snapshot.

BEGIN;

DELETE FROM dr_section;
INSERT INTO dr_section (section_id, name, path_prefix, description, sort_order) VALUES (1, '.github', '.github/', 'GitHub workflows — CI/CD automation', 0);
INSERT INTO dr_section (section_id, name, path_prefix, description, sort_order) VALUES (2, 'installer', 'installer/', 'WiX installer — Revit 2025/2026', 1);
INSERT INTO dr_section (section_id, name, path_prefix, description, sort_order) VALUES (3, 'installer-r27', 'installer-r27/', 'WiX installer — Revit 2027', 2);
INSERT INTO dr_section (section_id, name, path_prefix, description, sort_order) VALUES (4, 'shared', 'shared/', 'Shared code and utilities', 3);
INSERT INTO dr_section (section_id, name, path_prefix, description, sort_order) VALUES (5, 'spike', 'spike/', 'Spike/experimental code', 4);
INSERT INTO dr_section (section_id, name, path_prefix, description, sort_order) VALUES (6, 'src', 'src/', 'Core .NET source code — bootstrap, core, engine, UI, tests', 5);
INSERT INTO dr_section (section_id, name, path_prefix, description, sort_order) VALUES (7, 'docs', 'docs/', 'Project documentation and guides', 6);
INSERT INTO dr_section (section_id, name, path_prefix, description, sort_order) VALUES (8, 'tests', 'tests/', 'Headless UI regression tests and harnesses', 7);

COMMIT;
