// Profile.cs — RST profile model.
//
// On-disk shape mirrors the pyRevit RST profile JSON. Round-trip is
// fixture-tested in RST.Tests/Profiles/RoundTripTests.cs.

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace RST.Core.Profiles;

/// <summary>
/// A complete RST profile — a named, branded ribbon tab built from
/// existing Revit commands and add-ins, plus optional URL buttons.
/// </summary>
public sealed class Profile
{
    /// <summary>Schema version. v0 = pre-port pyRevit profiles (no field).</summary>
    [JsonPropertyName("schemaVersion")]
    public int SchemaVersion { get; set; }

    /// <summary>Stable UUID, generated by the profile manager.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>Display name shown in the profile picker.</summary>
    [JsonPropertyName("profile")]
    public string ProfileName { get; set; } = "";

    /// <summary>Revit ribbon tab title.</summary>
    [JsonPropertyName("tab")]
    public string Tab { get; set; } = "";

    /// <summary>Minimum RST runtime version this profile depends on.</summary>
    [JsonPropertyName("min_version")]
    public string MinVersion { get; set; } = "0.1.0";

    /// <summary>ISO-8601 export date.</summary>
    [JsonPropertyName("exportDate")]
    public string ExportDate { get; set; } = "";

    /// <summary>Panel-wide opacity 10-100; clamped on apply.</summary>
    [JsonPropertyName("panelOpacity")]
    public int PanelOpacity { get; set; } = 100;

    /// <summary>Add-ins this profile expects to be installed and enabled.</summary>
    [JsonPropertyName("requiredAddins")]
    public List<RequiredAddin> RequiredAddins { get; set; } = new();

    /// <summary>RSTify rules — tabs to hide / disable when this profile is active.</summary>
    [JsonPropertyName("hideRules")]
    public List<HideRule> HideRules { get; set; } = new();

    /// <summary>Named stacks (keyed by stack name). Slot of type "stack" references one.</summary>
    [JsonPropertyName("stacks")]
    public Dictionary<string, Stack> Stacks { get; set; } = new();

    /// <summary>Panels in display order, left-to-right after branding.</summary>
    [JsonPropertyName("panels")]
    public List<Panel> Panels { get; set; } = new();

    /// <summary>Optional per-profile branding overrides (logo, colors).</summary>
    [JsonPropertyName("branding")]
    public Branding? Branding { get; set; }
}

/// <summary>Required add-in descriptor — used to detect missing dependencies on load.</summary>
public sealed class RequiredAddin
{
    [JsonPropertyName("tabName")]      public string TabName     { get; set; } = "";
    [JsonPropertyName("displayName")]  public string? DisplayName { get; set; }
    [JsonPropertyName("addinFile")]    public string? AddinFile   { get; set; }
    [JsonPropertyName("addinId")]      public string? AddinId     { get; set; }
    /// <summary>
    /// Curated download URL baked in at profile-create time from
    /// addin_lookup.json (RST-022). Used by the Loader's QA modal to
    /// surface a clickable link when the addin is missing on the
    /// user's machine. Empty/null when the registry didn't know the
    /// addin or no URL was listed.
    /// </summary>
    [JsonPropertyName("url")]          public string? Url         { get; set; }
}

/// <summary>RSTify rule — a tab to hide while the profile is active.</summary>
public sealed class HideRule
{
    [JsonPropertyName("tab")]        public string Tab     { get; set; } = "";
    [JsonPropertyName("disabled")]   public bool   Disabled { get; set; }
}

public sealed class Stack
{
    [JsonPropertyName("tools")]
    public List<Slot> Tools { get; set; } = new();
}

public sealed class Panel
{
    [JsonPropertyName("name")]   public string Name   { get; set; } = "Panel";
    [JsonPropertyName("color")]  public string Color  { get; set; } = "#4f8ef7";
    [JsonPropertyName("cornerRadius")] public int? CornerRadius { get; set; }
    [JsonPropertyName("slots")]  public List<Slot> Slots { get; set; } = new();
}

/// <summary>
/// A panel slot. <see cref="SlotType"/> = <c>"tool"</c> for an inline button,
/// <c>"stack"</c> for a reference into <see cref="Profile.Stacks"/>.
/// </summary>
public sealed class Slot
{
    [JsonPropertyName("type")]         public string  SlotType    { get; set; } = "tool";
    [JsonPropertyName("name")]         public string  Name        { get; set; } = "";
    [JsonPropertyName("baseName")]     public string? BaseName    { get; set; }
    [JsonPropertyName("commandId")]    public string? CommandId   { get; set; }
    [JsonPropertyName("sourceTab")]    public string? SourceTab   { get; set; }
    [JsonPropertyName("sourcePanel")]  public string? SourcePanel { get; set; }
    [JsonPropertyName("iconFile")]     public string? IconFile    { get; set; }
}

public sealed class Branding
{
    [JsonPropertyName("logoFile")] public string? LogoFile { get; set; }
    [JsonPropertyName("url")]      public string? Url      { get; set; }
}
